madre(severina,felix_olivia).
madre(escolastica,martin).
madre(ana,alfonso).
madre(felix_olivia,olivia). 
madre(felix_olivia,mina). 
madre(isabel_navarro,beatriz).
madre(beatriz,jose). 
madre(olivia,luis). 
madre(beatriz,luis_alfonso). 
madre(beatriz,juan).
madre(beatriz,fernando).
madre(beatriz,marta_vargas). 
madre(mina,gisela). 
madre(mina,brenda). 
madre(marta_vargas,luis_ricardo). 
madre(marta_vargas,isabel). 
madre(marta_vargas,marta_estrada).
madre(laura,karla). 
madre(laura,diego). 
madre(esther,fernanda).
madre(esther,andre). 
madre(laura,gabriel).
madre(gisela,aura).  
padre(aureliano,felix_olivia).
padre(braulio,martin).
padre(amado,beatriz). 
padre(german,alfonso). 
padre(martin,olivia). 
padre(martin,mina).
padre(alfonso,jose).
padre(alfonso,luis_alfonso).
padre(alfonso,juan).
padre(alfonso,fernando).
padre(alfonso,marta_vargas).
padre(jose,luis). 
padre(mauricio,gisela). 
padre(mauricio,brenda).  
padre(ricardo,luis_ricardo). 
padre(ricardo,isabel). 
padre(ricardo,marta_estrada). 
padre(juan,karla). 
padre(juan,diego).
padre(juan,gabriel). 
padre(fernando,fernanda). 
padre(fernando,andre). 
padre(jose_luis,aura). 
hijo(X,Y):-padre(Y,X).
hijo(X,Y):-madre(Y,X).
abuelo(X,Y):-padre(Z,Y),padre(X,Z).
abuelo(X,Y):-padre(Z,Y),madre(X,Z).
abuelo(X,Y):-madre(Z,Y),padre(X,Z). 
abuelo(X,Y):-madre(Z,Y),madre(X,Z).
nieto(X,Y):-abuelo(Y,X).
hermano(X,Y):-padre(Z,X),hijo(Y,Z),X\=Y.
hermano(X,Y):-madre(Z,X),hijo(Y,Z),X\=Y.
primo(X,Y):-padre(Z,Y),tio(Z,X).
primo(X,Y):-madre(Z,Y),tio(Z,X).
tio(X,Y):-padre(B,Y),hermano(B,X),X\=Y.
tio(X,Y):-madre(B,Y),hermano(B,X),X\=Y.  
esposos(X,Y):-padre(X,Z),madre(Y,Z).
esposos(X,Y):-madre(X,Z),padre(Y,Z). 
sobrino(X,Y):-tio(Y,X),X\=Y.